name = input("What's your name? ")
age = int(input("What's your age? "))
gpa = float(input("How much gpa did you got on +2? "))
print("My name is "+name)
print("My age is "+str(age))
print("I got "+str(gpa)+" gpa")